# Generated by Django 4.2 on 2023-04-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(choices=[('ELECTRONICS', 'ELECTRONICS'), ('FASHION', 'FASHION'), ('BABY', 'BABY'), ('WOMEN', 'WOMEN'), ('MEN', 'MEN')], max_length=100)),
                ('image', models.ImageField(default='product.jpg', upload_to='product_images')),
            ],
        ),
    ]
